// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkns7bIjuS84kL9qG6kLrqbXcIDh3wUj0',
    appId: '1:260917072566:web:ff5bb9530023e58db98c17',
    messagingSenderId: '260917072566',
    projectId: 'flutter-accounts',
    authDomain: 'flutter-accounts.firebaseapp.com',
    storageBucket: 'flutter-accounts.firebasestorage.app',
    measurementId: 'G-3JN3PKLNEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnTN9AF8y8NhCE-OUy8XsBuGs7zgXSxA',
    appId: '1:260917072566:android:3f84d320c2ab7dd7b98c17',
    messagingSenderId: '260917072566',
    projectId: 'flutter-accounts',
    storageBucket: 'flutter-accounts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4JhfxMOur56CLfI4rJBOcApw0EgKPkjk',
    appId: '1:260917072566:ios:397bb80a4065f079b98c17',
    messagingSenderId: '260917072566',
    projectId: 'flutter-accounts',
    storageBucket: 'flutter-accounts.firebasestorage.app',
    iosBundleId: 'com.palpha.accountsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4JhfxMOur56CLfI4rJBOcApw0EgKPkjk',
    appId: '1:260917072566:ios:397bb80a4065f079b98c17',
    messagingSenderId: '260917072566',
    projectId: 'flutter-accounts',
    storageBucket: 'flutter-accounts.firebasestorage.app',
    iosBundleId: 'com.palpha.accountsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkns7bIjuS84kL9qG6kLrqbXcIDh3wUj0',
    appId: '1:260917072566:web:4dec0e87fb1689c6b98c17',
    messagingSenderId: '260917072566',
    projectId: 'flutter-accounts',
    authDomain: 'flutter-accounts.firebaseapp.com',
    storageBucket: 'flutter-accounts.firebasestorage.app',
    measurementId: 'G-MXWN18H37Z',
  );

}